# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Explicit requires for monorepo
require_relative '../node_modules/react-native/scripts/react_native_pods'

# Specify the Xcode project explicitly
project 'ChayoMobile.xcodeproj'

platform :ios, '15.1'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ChayoMobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Enable New Architecture for iOS
    :fabric_enabled => true,
    :new_arch_enabled => true
  )

  target 'ChayoMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix deployment target for all pods and main project
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Force iOS 15.1 for all targets
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        config.build_settings['TVOS_DEPLOYMENT_TARGET'] = '15.1'
        config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.15'
        config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
    
    # Also fix the main project targets
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        end
      end
    end
  end
end
